version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - app_net
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: nginx
    ports:
      - "5001:5000"
    networks:
      - app_net

  web2:
    image: nginx
    ports:
      - "5002:5000"
    networks:
      - app_net

  web3:
    image: nginx
    ports:
      - "5003:5000"
    networks:
      - app_net

  postgres1:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username1
      POSTGRES_PASSWORD: your_password1
      POSTGRES_DB: your_database1
    volumes:
      - ./data/postgres1:/var/lib/postgresql/data
    networks:
      - app_net

  postgres2:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username2
      POSTGRES_PASSWORD: your_password2
      POSTGRES_DB: your_database2
    volumes:
      - ./data/postgres2:/var/lib/postgresql/data
    networks:
      - app_net

  consul:
    image: consul
    networks:
      - app_net

  pg_bouncer:
    image: bitnami/pgbouncer:latest
    restart: always
    ports:
      - 6432:6432
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONSUL_KV_PREFIX=pgbouncer
      - AUTH_USER=your_pg_user
      - AUTH_PASSWORD=your_pg_password
    networks:
      - app_net

networks:
  app_net:
