version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - app_net
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: nginx
    ports:
      - 5001:5000
    networks:
      - app_net

  web2:
    image: nginx
    ports:
      - 5002:5000
    networks:
      - app_net

  web3:
    image: nginx
    ports:
      - 5003:5000
    networks:
      - app_net

  postgres1:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres1:/var/lib/postgresql/data
    networks:
      - app_net

  postgres2:
    image: postgres
    restart: always
    ports:
      - 8081:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres2:/var/lib/postgresql/data
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  consul:
    image: consul
    container_name: consul
    networks:
      - app_net

  pg_bouncer:
    image: brainsam/pgbouncer:1.7.2
    container_name: pgBouncer
    restart: always
    ports:
      - 6432:6432
    environment:
       - DB_USER= ${PGBOUNCER_USER}
       - DB_PASSWORD= ${PGBOUNCER_PASSWORD}
       - DB_HOST= ${PGBOUNCER_HOST}
       - DB_NAME= ${PGBOUNCER_DB}
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,dbuser
    networks:
      - app_net
    depends_on:
      - postgres1
      - postgres2

networks:
  app_net: