version: '3.8'

services:
 pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: cloud@ipt.pt
      PGADMIN_DEFAULT_PASSWORD: vagrant
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin