version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ../data/proxy_manager:/data
      - ../data/proxy_manager/letsencrypt:/etc/letsencrypt